# Example YAML configuration file for aish
# Place in ~/.config/aish/config.yaml

shell:
  default: /bin/bash
  args: []

syntax:
  substitution: "~{}"
  command: "!"
  question: "?"

error_handling:
  enabled: true
  ignore_exit_codes:
    grep: [1]
    diff: [1]
    test: [1]

ai:
  model: sonnet
  max_context_lines: 100
  timeout_seconds: 60

permissions:
  substitution: always_ask
  error_correction: always_ask
  command_generation: always_ask

history:
  enabled: true
  file: ~/.aish_history
  max_entries: 10000
  save_corrections: true

appearance:
  theme: default
  colors:
    ai_suggestion: cyan
    error: red
    success: green
    prompt: yellow
  indicators:
    processing: "⟳"
    ai_prefix: "✨"
    error_prefix: "❌"