# Advanced configuration example for aish
# Place in ~/.config/aish/config.yaml

# Shell configuration with custom arguments
shell:
  default: /usr/bin/zsh
  args: 
    - "--no-rcs"  # Skip RC files for faster startup

# Custom syntax markers
syntax:
  substitution: "#{}"    # Use #{} instead of ~{}
  command: "@"           # Use @ instead of !
  question: "??"         # Use ?? instead of ?
  accept: "yes"          # Use 'yes' instead of ++

# Enhanced error handling
error_handling:
  enabled: true
  suggest_only: false    # Don't auto-execute corrections
  max_retries: 2         # Retry failed commands up to 2 times
  ignore_exit_codes:
    grep: [1]            # grep returns 1 when no matches
    diff: [1]            # diff returns 1 when files differ
    test: [1]            # test returns 1 on false condition
    find: [1]            # find returns 1 when no files found
    which: [1]           # which returns 1 when command not found

# AI configuration with longer timeout
ai:
  model: sonnet          # or 'opus' for more powerful model
  max_context_lines: 200 # Include more context for better suggestions
  timeout_seconds: 120   # Allow 2 minutes for complex queries
  temperature: 0.7       # Adjust creativity (0.0-1.0)

# Granular permissions
permissions:
  substitution: filter   # Ask only for destructive operations
  error_correction: never_ask  # Auto-apply safe corrections
  command_generation: always_ask
  filters:
    allow:
      - "ls*"           # Always allow ls commands
      - "cat*"          # Always allow cat commands
      - "grep*"         # Always allow grep commands
    deny:
      - "rm -rf /*"     # Never allow root deletion
      - "*password*"    # Never auto-execute password commands

# History configuration
history:
  enabled: true
  file: ~/.aish_history
  max_entries: 50000
  save_corrections: true
  save_ai_interactions: true
  exclude_patterns:
    - "*password*"      # Don't save password commands
    - "*token*"         # Don't save token commands

# Appearance customization
appearance:
  theme: powerline      # options: default, minimal, powerline, fancy
  colors:
    ai_suggestion: brightcyan
    error: brightred
    success: brightgreen
    prompt: blue
    warning: yellow
    info: gray
  indicators:
    processing: "🔄"
    ai_prefix: "🤖"
    error_prefix: "⚠️"
    success_prefix: "✅"
    thinking: "💭"
  prompt_template: "{emoji} {cwd} {git_branch} {exit_code} ❯ "

# Advanced features
advanced:
  auto_complete: true   # Enable AI-powered auto-completion
  learn_from_usage: true # Adapt to user patterns
  cache_responses: true  # Cache AI responses for speed
  cache_ttl: 3600       # Cache for 1 hour
  
# Passthrough configuration for TUI apps
passthrough:
  commands:
    - vim
    - nano
    - emacs
    - less
    - more
    - htop
    - top
    - ssh
    - docker exec -it
    - kubectl exec
    - tmux
    - screen
  patterns:
    - "*curses*"
    - "*tui*"
    - "*interactive*"
  auto_detect: true

# Integration with external tools
integrations:
  git:
    enabled: true
    auto_commit_msg: true  # Generate commit messages
  docker:
    enabled: true
    suggest_commands: true
  kubernetes:
    enabled: true
    context_aware: true

# Development mode settings
development:
  log_level: info       # debug, info, warn, error
  log_file: ~/.aish.log
  metrics: false        # Collect usage metrics
  experimental: false   # Enable experimental features